[project]
name = 'ShieldedPools'
description = 'Privacy mixer contracts for Stacks blockchain'
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.shielded-stx-pool]
path = 'contracts/shielded-stx-pool.clar'
clarity_version = 4
epoch = 'latest'

[contracts.shielded-sip10-pool]
path = 'contracts/shielded-sip10-pool.clar'
clarity_version = 4
epoch = 'latest'

[contracts.mock-token4]
path = 'contracts/mock-token4.clar'
clarity_version = 4
epoch = 'latest'

[repl.analysis]
passes = [
    'call_checker',
    'check_checker',
]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
