/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qffxioveqaeozjoqegkp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmZnhpb3ZlcWFlb3pqb3FlZ2twIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwNjk0MjgsImV4cCI6MjA3NjY0NTQyOH0.ALaF34ZPBwdy-4jZ_Njt4kseD6bME-2tfcsznu65Fzc"